
title: João Maia
url: 'http://www.joaovrmaia.com'

#Profile information
name: João Maia
tagline: Software Engineer
pic: profile.png

#sidebar links
email: joao@joaovrmaia.com
phone: joaovrmaia (skype)
website: blog.joaovrmaia.com
linkedin: jvrmaia
github: jvrmaia
twitter: jvrmaia
